from bs4 import BeautifulSoup
import cowsay
import requests
import pandas as pd

# Онлайн-парсер
linkArray = ['https://tula.aif.ru/incidents/na_ulice_novomoskovska_muzhchina_ograbil_52-letnyuyu_prohozhuyu',
'https://tula.aif.ru/incidents/v_hode_pyanoy_ssory_zhitel_efremovskogo_rayona_ubil_66-letnego_znakomogo',
'https://tula.aif.ru/society/suvorov_stal_uchastnikom_vserossiyskogo_konkursa_po_sozdaniyu_gorodskoy_sredy',
'https://tula.aif.ru/society/iz-za_kommunalnoy_avarii_zhiteli_p_kosaya_gora_ostalis_bez_holodnoy_vody',
'https://tula.aif.ru/incidents/v_tulskoy_oblasti_arestovany_15_chlenov_prestupnogo_narkosoobshchestva',
'https://tula.aif.ru/incidents/prokuratura_obnaruzhila_nezakonnye_svalki_musora_v_zaokskom_rayone',
'https://tula.aif.ru/society/details/sud_oshtrafoval_tulyachku_kotoraya_oformila_kredit_na_umershuyu_mat',
'https://tula.aif.ru/society/v_novomoskovske_po_ryadu_ulic_ogranichat_ostanovku_i_stoyanku_transporta',
'https://tula.aif.ru/society/tulskie_kompanii_uzhestochili_pravila_povedeniya_v_socsetyah_dlya_sotrudnikov',
'https://tula.aif.ru/culture/6_aprelya_v_tule_proydyot_vystavka_dnevnik_podpolkovnika_lermontova',
'https://tula.aif.ru/incidents/za_moshennichestvo_s_vyplatami_po_invalidnosti_tulyak_poluchil_uslovnyy_srok',
'https://tula.aif.ru/health/oblastnye_vrachi_osmotreli_poryadka_240_zhiteley_belyovskogo_rayona',
'https://tula.aif.ru/incidents/zhitelnicu_novomoskovska_oshtrafovali_za_oskorblenie_sotrudnicy_wildberries',
'https://tula.aif.ru/incidents/v_tule_muzhchina_ukral_produkty_i_dengi_iz_stolovoy',
'https://tula.aif.ru/incidents/na_ul_chmutova_v_tule_voditel_krossovera_sbil_dorozhnyy_znak',
'https://tula.aif.ru/incidents/v_tule_na_reke_voronke_muzhchina_s_rebyonkom_provalilis_pod_lyod',
'https://tula.aif.ru/incidents/v_plavske_na_odnom_iz_predpriyatiy_progremel_vzryv',
'https://tula.aif.ru/society/details/v_novomoskovske_muzhchina_napal_na_policeyskih_sk_vozbudil_ugolovnoe_delo',
'https://tula.aif.ru/society/details/v_novomoskovske_muzhchina_zabarrikadirovalsya_v_kvartire_i_ugrozhal_podzhech_dom',
'https://tula.aif.ru/society/na_remont_dorog_v_novomoskovske_vydelyat_bolee_90_millionov_rubley',
'https://tula.aif.ru/health/za_sutki_v_tulskoy_oblasti_koronavirusom_zaboleli_37_chelovek',
'https://tula.aif.ru/incidents/zhiteli_novomoskovska_soobshchili_o_strelbe_na_ul_generala_belova',
'https://tula.aif.ru/incidents/v_bogorodicke_dve_zhenshchiny_obokrali_kvartiru_77-letney_pensionerki',
'https://tula.aif.ru/incidents/v_tulskoy_oblasti_osudili_migranta_kotoryy_otrezal_znakomomu_uho',
'https://tula.aif.ru/incidents/na_trasse_m-4_don_v_bogorodickom_rayone_kamaz_vrezalsya_v_gruzovik',
'https://tula.aif.ru/health/v_efremove_posle_kapremonta_otkrylas_poliklinika',
'https://tula.aif.ru/incidents/v_tulskoy_oblasti_bez_vesti_propal_34-letniy_muzhchina',
'https://tula.aif.ru/society/3_aprelya_v_tulskoy_oblasti_nachnyotsya_pozharoopasnyy_sezon',
'https://tula.aif.ru/culture/v_tule_sostoyalos_otkrytie_vserossiyskogo_festivalya_klubov_uchitel_goda',
'https://tula.aif.ru/society/details/v_tule_nachali_ubirat_svalku_musora_na_r_voronke_ryadom_s_tc_sarafan',
'https://tula.aif.ru/incidents/zhitelnica_suvorovskogo_rayona_pytalas_pronesti_v_sud_sportivnyy_pistolet',
'https://tula.aif.ru/incidents/doch_pogibshego_rabotnika_kmz_ne_mozhet_poluchit_polozhennye_strahovye_vyplaty',
'https://tula.aif.ru/health/v_tulskoy_oblasti_za_sutki_koronavirusom_zarazilis_38_chelovek',
'https://tula.aif.ru/incidents/crash/v_leninskom_rayone_tuly_nissan_stolknulsya_s_krossoverom_i_sletel_v_kyuvet',
'https://tula.aif.ru/society/housing/1_aprelya_v_tule_sostoitsya_obshchegorodskoy_subbotnik',
'https://tula.aif.ru/incidents/tulyaka_oshtrafovali_na_250_tys_rub_za_nezakonnye_arheologicheskie_raskopki',
'https://tula.aif.ru/incidents/tulyaki_zametili_svalku_musora_na_reke_voronke_ryadom_s_tc_sarafan',
'https://tula.aif.ru/society/persona/v_otnoshenii_tulskogo_sudi_mogut_vozbudit_ugolovnoe_delo_o_moshennichestve',
'https://tula.aif.ru/society/v_tulskoy_derevne_tihvinka_vremenno_ogranichat_dvizhenie_transporta',
'https://tula.aif.ru/incidents/v_tulskom_hozyaystve_nashli_narusheniya_pri_primenenii_pesticidov',
'https://tula.aif.ru/society/zapret_na_prodazhu_veypov_podderzhivayut_66_zhiteley_tuly',
'https://tula.aif.ru/society/details/v_kireevske_snesli_chastichno_obrushivshiysya_avariynyy_dom_na_ul_oktyabrskoy',
'https://tula.aif.ru/culture/events/tulyakov_priglashayut_na_prazdnovanie_5-letiya_tvorcheskogo_klastera_oktava',
'https://tula.aif.ru/society/v_ekologicheskom_reytinge_regionov_tulskaya_oblast_okazalas_na_71_meste',
'https://tula.aif.ru/society/housing/na_krasnoarmeyskom_prospekte_i_ul_karpova_v_tule_remontiruyut_dorogu',
'https://tula.aif.ru/incidents/v_tule_ishchut_propavshego_31-letnego_muzhchinu_s_irokezom',
'https://tula.aif.ru/incidents/zhitel_suvorovskogo_rayona_v_hode_ssory_izbil_znakomogo_obuhom_topora',
'https://tula.aif.ru/incidents/crash/v_tulskom_mikrorayone_severnaya_myza_stolknulis_avtobus_i_inomarka',
'https://tula.aif.ru/incidents/prokuratura_nachala_proverku_iz-za_musora_na_beregu_upy_v_tule',
'https://tula.aif.ru/sport/sportsmenka_iz_tuly_pobedila_na_pervenstve_evropy_po_tayskomu_boksu',
'https://tula.aif.ru/culture/events/v_yasnuyu_polyanu_priedet_rezhisser_pavel_lungin',
'https://tula.aif.ru/health/v_tulskoy_oblasti_za_sutki_koronavirus_vyyavili_u_29_chelovek',
'https://tula.aif.ru/incidents/crash/posle_stolknoveniya_s_otboynikom_pod_tuloy_volkswagen_ostalsya_bez_kolyos',
'https://tula.aif.ru/society/za_otkaz_chistit_sneg_v_tule_predprinimatelya_vklyuchili_v_chyornyy_spisok',
'https://tula.aif.ru/incidents/v_yasnogorske_budut_sudit_moskvicha_za_iznasilovanie_i_ubiystvo_pensionerki',
'https://tula.aif.ru/society/details/moment_dtp_s_tramvaem_i_furoy_v_tule_popal_na_video',
'https://tula.aif.ru/society/bolee_9_5_tys_tulskih_pensionerov_poluchayut_selskuyu_nadbavku_k_pensii',
'https://tula.aif.ru/incidents/postradavshuyu_v_dtp_devochku_dostavili_v_bolnicu_tuly_vertolyotom_sanaviacii',
'https://tula.aif.ru/incidents/crash/v_dtp_s_gruzovikom_na_ul_metallurgov_v_tule_postradali_dva_cheloveka',
'https://tula.aif.ru/incidents/bezrabotnyy_49-letniy_tulyak_ukral_iz_magazina_produkty_pitaniya',
'https://tula.aif.ru/incidents/tulyachka_neskolko_mesyacev_nezakonno_poluchala_pensiyu_umershih_roditeley',
'https://tula.aif.ru/society/housing/v_tule_16_i_25_aprelya_ogranichat_dvizhenie_transporta',
'https://tula.aif.ru/incidents/zhitelya_aleksina_oshtrafovali_za_prodazhu_alkogolya_bez_akciznyh_marok',
'https://tula.aif.ru/incidents/v_tulskoy_oblasti_ishchut_propavshego_31-letnego_muzhchinu',
'https://tula.aif.ru/society/events/tulyachke_margarite_lerman_prisvoili_pochyotnoe_zvanie_zasluzhennyy_vrach_rf',
'https://tula.aif.ru/incidents/crash/na_ul_oktyabrskoy_v_donskom_voditel_vaza_sbil_peshehoda',
'https://tula.aif.ru/sport/tulyak_zanyal_pervoe_mesto_na_vserossiyskih_sorevnovaniyah_po_boksu',
'https://tula.aif.ru/society/v_tulskoy_oblasti_iz-za_tumana_obyavili_meteopreduprezhdenie',
'https://tula.aif.ru/incidents/v_uzlovoy_24-letnyuyu_devushku_budut_sudit_za_krazhu_i_ubiystvo',
'https://tula.aif.ru/society/na_trasse_m-4_don_v_tulskoy_oblasti_perekroyut_dvizhenie_po_tryom_mostam',
'https://tula.aif.ru/incidents/crash/v_venyovskom_rayone_na_trasse_m-4_don_voditel_hyundai_pogib_v_dtp',
'https://tula.aif.ru/society/v_tule_mebelnaya_kompaniya_zaplatit_klientu_bolee_100_tys_rub_kompensacii',
'https://tula.aif.ru/health/za_minuvshie_sutki_v_tulskoy_oblasti_koronavirusom_zaboleli_28_chelovek',
'https://tula.aif.ru/society/za_proshedshie_vyhodnye_tulskie_inspektory_poymali_35_netrezvyh_voditeley',
'https://tula.aif.ru/society/events/nazvana_srednyaya_stoimost_bileta_v_tulskiy_teatr',
'https://tula.aif.ru/money/tulskim_soiskatelyam_predlagayut_vakansiyu_s_zarplatoy_do_400_tys_rubley',
'https://tula.aif.ru/incidents/tulskih_shkolnikov_i_detey_v_sadu_kormili_mintaem_somnitelnogo_kachestva',
'https://tula.aif.ru/society/tulskaya_oblast_okazalas_na_42_meste_v_reytinge_po_zarplatam_v_provincii',
'https://tula.aif.ru/society/v_tule_kazhdaya_pyataya_kompaniya_polzuetsya_uslugami_samozanyatyh',
'https://tula.aif.ru/incidents/crash/v_tule_na_ul_lozhevoy_inomarka_vletela_v_ograzhdenie',
'https://tula.aif.ru/incidents/zhitelya_plavskogo_rayona_arestovali_na_10_sutok_za_pyanoe_vozhdenie_bez_prav',
'https://tula.aif.ru/culture/v_tule_proshyol_koncert_muzykalnoy_sbornoy_rossii_iz_sankt-peterburga',
'https://tula.aif.ru/incidents/avtolihach_iz_yasnogorska_nakopil_dolg_po_184_shtrafam_gibdd',
'https://tula.aif.ru/society/tulyakam_rasskazali_chto_delat_pri_obnaruzhenii_narkotikov_na_dachnom_uchastke',
'https://tula.aif.ru/society/housing/v_tule_organizuyut_podezd_k_gorodskim_kladbishcham_pered_radonicey',
'https://tula.aif.ru/culture/tulyakov_priglashayut_na_vystavku_fotografiy_iz_lichnoy_kollekcii_v_veresaeva',
'https://tula.aif.ru/society/tulskie_stroiteli_vosstanavlivayut_infrastrukturu_i_zhilyo_v_mariupole',
'https://tula.aif.ru/incidents/v_tule_pod_vidom_bukmekerskoy_kontory_rabotal_igornyy_klub',
'https://tula.aif.ru/incidents/v_tule_zaderzhali_moshennicu_kotoraya_ukrala_u_pensionerov_pochti_2_mln_rubley',
'https://tula.aif.ru/incidents/prokuratura_nashla_narusheniya_v_feldsherskom_punkte_chernskogo_rayona',
'https://tula.aif.ru/society/tulskie_rabotniki_kultury_v_srednem_zarabatyvayut_53_3_tys_rubley_v_mesyac',
'https://tula.aif.ru/society/housing/na_novomoskovskom_shosse_v_tule_ogranichat_ostanovku_i_stoyanku_transporta',
'https://tula.aif.ru/incidents/v_dtp_pod_efremovom_stolknulis_toyota_i_kamaz',
'https://tula.aif.ru/culture/muzey-zapovednik_kulikovo_pole_vypustil_nastolnuyu_igru_dlya_detey',
'https://tula.aif.ru/society/yasnaya_polyana_ishchet_podryadchika_dlya_restavracii_muzeynyh_predmetov',
'https://tula.aif.ru/politic/ukazom_prezidenta_rf_tulskiy_gubernator_poluchil_novoe_naznachenie',
'https://tula.aif.ru/society/housing/26_marta_iz-za_futbolnogo_matcha_v_tule_ogranichat_prodazhu_alkogolya',
'https://tula.aif.ru/incidents/v_novomoskovske_neizvestnye_podbrosili_v_podezd_doma_dvuh_cherepah',
'https://tula.aif.ru/society/arestovannoe_imushchestvo_tulskih_dolzhnikov_uydyot_s_molotka_31_marta',
'https://tula.aif.ru/incidents/v_tule_eks-sotrudnica_gibdd_nezakonno_vydala_13_voditelskih_udostovereniy',
'https://tula.aif.ru/society/housing/avtostoyanku_na_ul_novomoskovskoy_v_tule_uberut_po_resheniyu_suda',
'https://tula.aif.ru/incidents/tulskiy_predprinimatel_poydyot_pod_sud_za_prodazhu_nemarkirovannyh_sigaret',
'https://tula.aif.ru/society/tulskie_semi_budut_poluchat_vyplatu_iz_matkapitala_v_edinyy_den_dostavki',
'https://tula.aif.ru/incidents/v_odoeve_pyanyy_muzhchina_udaril_inspektora_dps_i_sorval_s_nego_pogon',
'https://tula.aif.ru/incidents/zhitelya_plavska_oshtrafovali_na_100_tys_rubley_za_krazhu_deneg_s_chuzhoy_karty',
'https://tula.aif.ru/health/za_proshedshie_sutki_v_tulskoy_oblasti_koronavirusom_zaboleli_45_chelovek',
'https://tula.aif.ru/incidents/crash/v_chernskom_rayone_v_dtp_s_motorollerom_postradali_dva_cheloveka',
'https://tula.aif.ru/society/housing/na_tulskiy_predpriyatiyah_opk_uvelichilis_obyomy_proizvodstva_izdeliy',
'https://tula.aif.ru/health/v_den_borby_s_tuberkulezom_tulyakov_priglashayut_na_besplatnuyu_flyuorografiyu',
'https://tula.aif.ru/society/details/sledovateli_ustanavlivayut_obstoyatelstva_obrusheniya_steny_doma_v_kireevske',
'https://tula.aif.ru/society/details/prokuratura_organizovala_proverku_posle_obrusheniya_steny_doma_v_kireevske',
'https://tula.aif.ru/incidents/v_kireevske_chastichno_obrushilsya_fasad_zhilogo_dvuhetazhnogo_doma',
'https://tula.aif.ru/society/housing/v_tule_blagoustraivayut_skver_pamyati_tulyakov_pogibshih_v_lokalnyh_voynah',
'https://tula.aif.ru/incidents/v_tule_na_ul_tihmyanova_fura_zastryala_na_tramvaynyh_putyah',
'https://tula.aif.ru/incidents/tulyaka_osudili_na_4_goda_za_moshennichestvo_s_poezdkami_k_dedu_morozu',
'https://tula.aif.ru/society/zhitel_aleksina_pouchastvoval_v_teleshou_andreya_malahova_pesni_ot_vsey_dushi',
'https://tula.aif.ru/society/otkazatsya_ot_svoego_ayfona_radi_raboty_gotovy_48_tulyakov',
'https://tula.aif.ru/sport/tulskiy_akm_obygral_tyumenskiy_rubin_i_sravnyal_schyot_v_serii',
'https://tula.aif.ru/incidents/sud_obyazal_tulskiy_sanatoriy_vernut_dengi_klientam_za_isporchennyy_otdyh',
'https://tula.aif.ru/sport/v_tulskoy_oblasti_sostoitsya_pervenstvo_rossii_po_podvodnomu_sportu',
'https://tula.aif.ru/incidents/prokuratura_nashla_narusheniya_v_podzemnom_perehode_na_ul_kaminskogo_v_tule',
'https://tula.aif.ru/incidents/inostranec_ukral_s_tulskogo_zavoda_metall_na_1_1_mln_rubley',
'https://tula.aif.ru/incidents/crash/v_posyolke_pervomayskiy_pod_kolyosa_gazeli_popala_15-letnyaya_devochka',
'https://tula.aif.ru/society/details/v_tule_sledovateli_provodyat_proverku_po_faktu_smerti_muzhchiny_v_tire',
'https://tula.aif.ru/health/41_zhitel_tulskoy_oblasti_zabolel_koronavirusom_za_minuvshie_sutki',
'https://tula.aif.ru/incidents/crash/v_aleksine_pyanyy_voditel_sletel_v_kyuvet_i_vrezalsya_v_derevo',
'https://tula.aif.ru/incidents/v_tulskom_strelkovom_klube_nashli_trup_muzhchiny',
'https://tula.aif.ru/incidents/v_kimovskom_rayone_zhenshchina_udarila_nozhom_sozhitelya_v_hode_pyanoy_ssory',
'https://tula.aif.ru/incidents/v_tule_evakuirovali_universitet_yusticii_na_prospekte_lenina',
'https://tula.aif.ru/incidents/crash/v_tule_na_prospekte_lenina_honda_vletela_v_ograzhdenie',
'https://tula.aif.ru/society/v_tulskoy_oblasti_narusheniya_po_blagoustroystvu_ustranyat_v_10-dnevnyy_srok',
'https://tula.aif.ru/incidents/za_krazhu_deneg_iz_bankomata_tulyak_zaplatit_15_tys_rubley_shtrafa',
'https://tula.aif.ru/society/v_tulskoy_oblasti_16_klassov_ushli_na_karantin_iz-za_zabolevaemosti_orvi',
'https://tula.aif.ru/society/v_fevrale_tulyaki_pozvonili_v_kontakt-centr_minzdrava_bolee_160_tysyach_raz',
'https://tula.aif.ru/society/bolelshchik_tulskogo_arsenala_obyavil_golodovku_do_pobedy_komandy',
'https://tula.aif.ru/society/housing/na_ul_liteynoy_v_tule_ogranichat_ostanovku_i_stoyanku_avtomobiley',
'https://tula.aif.ru/society/tulskiy_gubernator_obratil_vnimanie_na_vazhnost_sostoyaniya_dorog_posle_zimy',
'https://tula.aif.ru/society/gubernator_podaril_tulskomu_suvorovskomu_voennomu_uchilishchu_4_kvadrokoptera',
'https://tula.aif.ru/society/housing/v_tule_na_magistralnyh_ulicah_privedut_v_poryadok_fasady_zdaniy_i_gazony',
'https://tula.aif.ru/society/na_ploshchadi_lenina_v_tule_organizuyut_fan-zonu_dlya_prosmotra_hokkeynogo_matcha',
'https://tula.aif.ru/incidents/tulskaya_prokuratura_vyyavila_narusheniya_v_dvuh_restoranah_na_iskre',
'https://tula.aif.ru/incidents/tulskie_inspektory_poymali_29_netrezvyh_voditeley_za_minuvshie_vyhodnye',
'https://tula.aif.ru/incidents/crash/v_dtp_na_ul_demonstracii_v_tule_postradali_dva_cheloveka',
'https://tula.aif.ru/incidents/prokuratura_proveryaet_zakonnost_rasporyazheniya_nezhilymi_pomeshcheniyami_v_tulgu',
'https://tula.aif.ru/health/za_sutki_v_tulskoy_oblasti_koronavirusom_zaboleli_39_chelovek',
'https://tula.aif.ru/society/details/operativnika_otdela_mvd_yasnogorska_zaklyuchili_pod_domashniy_arest',
'https://tula.aif.ru/incidents/v_tulskoy_oblasti_ishchut_52-letnego_muzhchinu_propavshego_nedelyu_nazad',
'https://tula.aif.ru/incidents/crash/v_dtp_v_venyovskom_rayone_postradali_dvoe_vzroslyh_i_7-letniy_rebyonok',
'https://tula.aif.ru/society/80_soiskateley_iz_tuly_proveryayut_rabotodateley_pered_sobesedovaniem',
'https://tula.aif.ru/money/tulskaya_oblast_zanyala_50_mesto_v_reytinge_regionov_po_zarplatam',
'https://tula.aif.ru/society/23_marta_glavnyy_sudebnyy_pristav_otvetit_na_voprosy_tulyakov',
'https://tula.aif.ru/incidents/v_shchyokine_zhenshchina_ukrala_iz_magazina_predmety_lichnoy_gigieny',
'https://tula.aif.ru/incidents/tulyak_poluchil_25_chasov_obyazatelnyh_rabot_za_neuplatu_shtrafa',
'https://tula.aif.ru/society/sud_obyazal_belyovskuyu_administraciyu_ubrat_nezakonnye_svalki',
'https://tula.aif.ru/society/dom_tolstogo_v_yasnoy_polyane_budet_zakryt_dlya_poseshcheniya_s_4_po_14_aprelya',
'https://tula.aif.ru/society/housing/na_borbu_s_borshchevikom_sosnovskogo_v_tule_potratyat_pochti_5_mln_rubley',
'https://tula.aif.ru/society/v_tule_rosgvardeycy-uchastniki_svo_poluchili_oborudovanie_i_ekipirovku',
'https://tula.aif.ru/sport/v_tule_sostoitsya_chempionat_oblasti_po_darts',
'https://tula.aif.ru/sport/v_tule_startoval_detskiy_kubok_po_dvorovomu_hokkeyu_shag_v_zhizn',
'https://tula.aif.ru/incidents/crash/v_dtp_na_venyovskom_shosse_v_tule_postradal_29-letniy_voditel',
'https://tula.aif.ru/society/persona/pevec_shaman_popal_v_chyornyy_spisok_latvii_za_podderzhku_svo',
'https://tula.aif.ru/society/housing/na_molodyozhnom_bulvare_v_tule_prodolzhatsya_raboty_po_blagoustroystvu',
'https://tula.aif.ru/society/v_tule_roditeli_shkolnikov_sdali_ege_po_russkomu_yazyku',
'https://tula.aif.ru/incidents/za_pobeg_iz_tulskoy_kolonii_osuzhdyonnogo_lishili_svobody_na_2_goda',
'https://tula.aif.ru/incidents/v_efremovskom_rayone_povtorno_podtopleny_18_priusadebnyh_uchastkov',
'https://tula.aif.ru/health/za_sutki_v_tulskoy_oblasti_koronavirusom_zaboleli_49_chelovek',
'https://tula.aif.ru/culture/events/v_arsenevo_sostoyalos_otkrytie_kraevedcheskogo_muzeya_posle_kapremonta',
'https://tula.aif.ru/incidents/v_chernskom_rayone_spasateli_obezvredili_boepripasy_vremyon_vov',
'https://tula.aif.ru/society/gubernator_tulskoy_oblasti_raskritikoval_podgotovku_k_pavodku_v_regione',
'https://tula.aif.ru/incidents/v_donskom_sud_na_3_mesyaca_zakryl_kafe_v_kotorom_otravilis_shaurmoy',
'https://tula.aif.ru/society/s_4_aprelya_tulyaki_smogut_podat_zayavleniya_na_putyovki_v_detskie_lagerya',
'https://tula.aif.ru/incidents/zhitelya_shchyokina_budut_sudit_za_ubiystvo_znakomogo_metallicheskoy_truboy',
'https://tula.aif.ru/sport/v_tule_prohodyat_sorevnovaniya_po_voleybolu_serebryanyy_myach',
'https://tula.aif.ru/society/events/v_tule_rosgvardeycy_poluchili_klyuchi_ot_novyh_sluzhebnyh_avtomobiley',
'https://tula.aif.ru/incidents/tulyachku_oshtrafovali_za_moshennichestvo_s_chernobylskimi_vyplatami',
'https://tula.aif.ru/society/v_etom_godu_v_novomoskovske_blagoustroyat_berezovuyu_roshchu_beresta',
'https://tula.aif.ru/incidents/crash/v_tule_na_ul_kutuzova_renault_stolknulsya_s_marshrutkoy',
'https://tula.aif.ru/society/mchs_preduprezhdaet_tulyakov_o_gololedice_tumane_i_mokrom_snege',
'https://tula.aif.ru/society/housing/18_marta_iz-za_sportivnogo_meropriyatiya_v_tule_ogranichat_dvizhenie_transporta',
'https://tula.aif.ru/society/housing/v_tule_n_ul_probnoy_izmenitsya_organizaciya_dorozhnogo_dvizheniya',
'https://tula.aif.ru/society/zhiteley_tulskoy_oblasti_preduprezhdayut_ob_usilenii_vetra',
'https://tula.aif.ru/health/18_marta_tulyakov_priglashayut_na_besplatnyy_onkoskrining',
'https://tula.aif.ru/health/za_sutki_39_zhiteley_tulskoy_oblasti_zarazilis_koronavirusom',
'https://tula.aif.ru/incidents/v_aleksine_proizoshlo_avariynoe_otklyuchenie_podachi_vodosnabzheniya',
'https://tula.aif.ru/incidents/v_suvorovskom_rayone_migrant_do_smerti_izbil_znakomogo_v_hode_pyanoy_ssory',
'https://tula.aif.ru/incidents/v_tulskom_posyolke_molodyozhnyy_stolknulis_scania_i_bmw',
'https://tula.aif.ru/incidents/zhitelnica_suvorovskogo_rayona_do_smerti_zabila_70-letnego_znakomogo',
'https://tula.aif.ru/society/persona/pevec_shaman_rasskazal_kak_napisal_pesnyu_ya_russkiy',
'https://tula.aif.ru/incidents/crash/v_tule_na_ul_oktyabrskoy_legkovushka_stolknulas_s_avtobusom',
'https://tula.aif.ru/sport/tulskie_sportsmenki_zavoevali_medali_na_sorevnovaniyah_po_karate',
'https://tula.aif.ru/society/events/tulyakov_priglashayut_na_istoricheskuyu_vystavku_milliony_let_pod_zemley',
'https://tula.aif.ru/society/details/tulskiy_sud_priznal_vinovnymi_v_moshennichestve_eks-doznavatelya_i_advokata',
'https://tula.aif.ru/incidents/tulyachku_oshtrafovali_na_40_tys_rubley_za_napadenie_na_policeyskogo',
'https://tula.aif.ru/society/details/tulyachku_napavshuyu_na_vracha-pediatra_otpravyat_na_prinuditelnoe_lechenie',
'https://tula.aif.ru/culture/kulturno-turisticheskiy_potencial_tulskoy_oblasti_predstavili_v_stolice',
'https://tula.aif.ru/incidents/v_tule_direktora_stroitelnyh_kompaniy_arestovali_za_moshennichestvo',
'https://tula.aif.ru/society/housing/v_tule_na_centralnom_rynke_nachali_demontirovat_torgovye_ryady',
'https://tula.aif.ru/society/housing/iz-za_pogodnyh_usloviy_v_tulskih_parkah_zakryli_katki',
'https://tula.aif.ru/society/edinoe_posobie_poluchili_pochti_24_tysyach_zhiteley_tulskoy_oblasti',
'https://tula.aif.ru/society/v_tulskoy_oblasti_roditeli_uchastnikov_svo_poluchat_lgotu_na_dogazifikaciyu',
'https://tula.aif.ru/incidents/plavskim_medikam_ponadobilas_pomoshch_spasateley_chtoby_doehat_do_pacientki',
'https://tula.aif.ru/incidents/za_vyhodnye_tulskie_inspektory_zaderzhali_20_pyanyh_voditeley',
'https://tula.aif.ru/sport/19_marta_v_tule_sostoitsya_match_mezhdu_tulicey_i_leningradkoy',
'https://tula.aif.ru/incidents/crash/v_tule_na_ul_staronikitskoy_sbili_45-letnyuyu_zhenshchinu',
'https://tula.aif.ru/health/za_sutki_v_tulskoy_oblasti_vyyavili_41_sluchay_zabolevaniya_koronavirusom',
'https://tula.aif.ru/money/v_reytinge_zakreditovannosti_naseleniya_tulskaya_oblast_zanyala_33_mesto',
'https://tula.aif.ru/society/23_marta_v_tulskoy_oktave_sostoitsya_psihologicheskiy_forum_podsoznanie',
'https://tula.aif.ru/incidents/crash/v_dtp_na_trasse_m-2_v_plavskom_rayone_postradali_neskolko_chelovek',
'https://tula.aif.ru/society/v_tulskoy_oblasti_ne_hvataet_anesteziologov_vrachey_uzi_i_infekcionistov',
'https://tula.aif.ru/incidents/v_efremovskom_rayone_iz-za_pavodka_uroven_vody_podnyalsya_na_1_3_metra',
'https://tula.aif.ru/health/v_tulskih_brigadah_skoroy_pomoshchi_mogut_poyavitsya_portativnye_uzi-apparaty',
'https://tula.aif.ru/culture/v_bogorodickom_dvorce-muzee_sostoitsya_lekciya_posvyashchennaya_tulskomu_govoru',
'https://tula.aif.ru/incidents/v_tulskom_krivoluche_nochyu_ulichnoe_osveshchenie_rabotalo_s_pereboyami',
'https://tula.aif.ru/society/housing/v_tule_snesut_avtomoyku_dlya_stroitelstva_dvuhurovnevoy_razvyazki',
'https://tula.aif.ru/incidents/v_tule_voditel_taksi_hotel_zabrat_sebe_smartfon_ostavlennyy_passazhirom',
'https://tula.aif.ru/society/housing/v_tulskom_centralnom_parke_perekryli_chast_katka_na_ryabinovoy_allee',
'https://tula.aif.ru/incidents/crash/v_dtp_v_plavskom_rayone_postradali_tri_cheloveka',
'https://tula.aif.ru/incidents/36-letnyaya_tulyachka_urala_u_rodnoy_babushki_zolotoy_braslet',
'https://tula.aif.ru/health/glavnyy_tulskiy_nefrolog_rasskazala_kak_sohranit_zdorove_pochek',
'https://tula.aif.ru/society/events/v_tulskoy_oblasti_startoval_god_pedagoga_i_nastavnika',
'https://tula.aif.ru/society/details/v_tule_s_eks-dekana_yuridicheskogo_vuza_vzyskali_206_tys_rubley_za_vzyatki',
'https://tula.aif.ru/society/tulyakov_predupredili_o_novoy_moshennicheskoy_sheme_s_mobilnymi_prilozheniyami',
'https://tula.aif.ru/society/details/administraciya_tuly_prokommentirovala_proval_na_doroge_u_centralnogo_parka',
'https://tula.aif.ru/health/v_tulskoy_oblasti_za_sutki_vyyavili_55_sluchaev_zarazheniya_koronavirusom',
'https://tula.aif.ru/society/education_science/tulskih_shkolnikov_priglasili_na_olimpiadu_po_finansovoy_gramotnosti',
'https://tula.aif.ru/incidents/v_tule_na_ul_rabochego_polka_zhiteli_obnaruzhili_ogromnuyu_dyru_na_doroge',
'https://tula.aif.ru/incidents/na_prospekte_lenina_v_tule_muzhchina_gulyal_po_proezzhey_chasti_i_meshal_dvizheniyu',
'https://tula.aif.ru/society/sudebnye_pristavy_pomogli_tulyaku_vosstanovit_pravo_na_obshchenie_s_docheryu',
'https://tula.aif.ru/incidents/crash/v_troynom_dtp_v_venyovskom_rayone_postradali_neskolko_chelovek',
'https://tula.aif.ru/money/molodye_tulskie_predprinimateli_mogut_poluchit_dopolnitelnuyu_podderzhku',
'https://tula.aif.ru/society/education_science/v_tulskoy_oblasti_sostoitsya_mezhdunarodnyy_forum_inzhenery_budushchego',
'https://tula.aif.ru/society/housing/12_marta_iz-za_futbolnogo_matcha_v_tule_ogranichat_prodazhu_alkogolya',
'https://tula.aif.ru/incidents/v_tulskoy_oblasti_ishchut_propavshego_47-letnego_muzhchinu',
'https://tula.aif.ru/society/s_nachala_goda_nuzhdayushchimsya_tulskim_semyam_vyplatili_bolee_459_mln_rubley',
'https://tula.aif.ru/society/predstavitelem_tulskogo_otryada_lizaalert_naznachen_dmitriy_ryabov',
'https://tula.aif.ru/society/posle_vmeshatelstva_prokuratury_tulyachke_vyplatili_pensiyu_umershey_materi',
'https://tula.aif.ru/incidents/crash/v_kimovskom_rayone_82-letnyaya_zhenshchina_popala_pod_kolyosa_uaza',
'https://tula.aif.ru/society/details/glava_administracii_efremova_nazval_prichinu_gromkih_hlopkov_v_gorode',
'https://tula.aif.ru/health/v_tulskoy_oblasti_za_sutki_koronavirusom_zaboleli_69_chelovek',
'https://tula.aif.ru/society/na_reke_tulice_prohodyat_protivopavodkovye_meropriyatiya',
'https://tula.aif.ru/incidents/crash/v_tule_na_ul_dmitriya_ulyanova_sbili_zhenshchinu-peshehoda',
'https://tula.aif.ru/society/zhitelya_shchyokinskogo_rayona_osudili_na_1_god_za_krazhi_iz_dvuh_magazinov',
'https://tula.aif.ru/society/housing/v_tule_na_novomoskovskom_shosse_planiruyut_postroit_bazu_avtoparka',
'https://tula.aif.ru/incidents/zhitel_aleksina_nanyos_sebe_nozhevye_raneniya_iz-za_ssory_s_rodstvennikami',
'https://tula.aif.ru/society/predstavitel_tulskogo_poiskovogo_otryada_lizaalert_pokinul_svoy_post',
'https://tula.aif.ru/incidents/zhiteli_efremova_uslyshali_gromkie_hlopki_ot_kotoryh_drebezzhali_okna_v_domah',
'https://tula.aif.ru/society/13_marta_zhiteli_tuly_smogut_zadat_voprosy_sudebnomu_pristavu',
'https://tula.aif.ru/society/details/propavshego_v_tulskoy_oblasti_14-letnego_podrostka_nashli_zhivym',
'https://tula.aif.ru/society/tulyachke_naznachili_60_chasov_obyazatelnyh_rabot_za_neuplatu_alimentov',
'https://tula.aif.ru/sport/v_pervenstve_rossii_po_pauerliftingu_tulyak_zavoeval_bronzovuyu_medal',
'https://tula.aif.ru/sport/tulskaya_akademiya_mihaylova_vyshla_v_chetvertfinal_kubka_petrova',
'https://tula.aif.ru/incidents/v_tule_na_zelenstroe_iz-za_beshoznyh_sumok_ocepili_ostanovku',
'https://tula.aif.ru/incidents/crash/v_tule_na_inshinskom_proezde_stolknulis_dve_gazeli',
'https://tula.aif.ru/incidents/v_tule_na_ul_kirova_zhenshchina_pregradila_dorogu_avtomobilyu_i_plyunula_na_kapot',
'https://tula.aif.ru/incidents/crash/v_novomoskovske_pyanaya_zhenshchina_za_rulyom_chevrolet_ustroila_troynoe_dtp',
'https://tula.aif.ru/society/20_zhenshchin_v_tulskoy_oblasti_rabotayut_v_optovoy_i_roznichnoy_torgovle',
'https://tula.aif.ru/incidents/crash/v_tule_na_peresechenii_ulic_9_maya_i_smidovich_stolknulis_dve_legkovushki',
'https://tula.aif.ru/society/v_kanun_8_marta_v_tule_nachali_prodavat_vesennie_cvety',
'https://tula.aif.ru/health/za_stuki_v_tulskoy_oblasti_vyyavili_74_sluchaya_zabolevaniya_koronavirusom',
'https://tula.aif.ru/incidents/v_tule_inspektory_spasli_muzhchinu_kotoryy_peshkom_shyol_do_orlovskoy_oblasti',
'https://tula.aif.ru/society/v_novom_korpuse_tulskogo_perinatalnogo_centra_rodilis_okolo_4800_malyshey',
'https://tula.aif.ru/society/nabor_rybaka_i_pesnya_tulyachki_nazvali_samye_neobychnye_podarki_na_8_marta',
'https://tula.aif.ru/incidents/v_novomoskovske_sud_prigovoril_narkotorgovca_iz_penzy_k_13_godam_kolonii',
'https://tula.aif.ru/society/v_tulskoy_oblasti_obsudili_voprosy_cifrovizacii_voenkomatov_v_cfo',
'https://tula.aif.ru/society/v_tule_proshlo_nagrazhdenie_predprinimateley_za_podderzhku_voennosluzhashchih',
'https://tula.aif.ru/society/tulskie_molodozhyony_mogut_poluchit_elektronnyy_sertifikat_molodaya_semya',
'https://tula.aif.ru/incidents/tulyak_pytalsya_pronesti_v_koloniyu_narkotiki_vnutri_upakovki_tvorozhnoy_massy',
'https://tula.aif.ru/society/events/zdanie_muzeya_oruzhiya_v_tulskom_kremle_otkroetsya_9_marta_posle_remonta',
'https://tula.aif.ru/society/deputaty_predlozhili_uvelichit_vremya_prodazhi_alkogolya_v_tulskoy_oblasti',
'https://tula.aif.ru/society/v_donskom_otkrylas_fotovystavka_monet_petra_tvorenya',
'https://tula.aif.ru/society/v_tulskoy_oblasti_invalidam_kompensiruyut_50_stoimosti_polisa_osago',
'https://tula.aif.ru/society/details/v_dtp_s_perevyortyshem_na_ul_metallurgov_v_tule_postradal_chelovek',
'https://tula.aif.ru/society/details/v_tule_sud_rassmotrel_ugolovnoe_delo_svyazannoe_s_ubiystvom_dari_duginoy',
'https://tula.aif.ru/incidents/crash/v_tule_na_ul_metallurgov_perevernulsya_avtomobil',
'https://tula.aif.ru/society/v_tulskoy_oblasti_opublikovany_aktualnye_k_8_marta_vakansii',
'https://tula.aif.ru/health/v_tulskoy_oblasti_za_sutki_koronavirusom_zaboleli_80_chelovek',
'https://tula.aif.ru/incidents/tulyak_snyal_video_opasnoy_ezdy_shashechkami_na_vostochnom_obvode',
'https://tula.aif.ru/society/master_iz_aleksina_ustanovil_na_elbruse_snezhnuyu_skulpturu_lisy_muhi',
'https://tula.aif.ru/society/housing/v_tule_7_marta_vremenno_ogranichat_ostanovku_i_stoyanku_transporta',
'https://tula.aif.ru/incidents/pri_pogone_so_strelboy_za_lihachom_v_tulskoy_oblasti_postradala_zhenshchina',
'https://tula.aif.ru/incidents/crash/v_uzlovskom_rayone_avtomobil_volkswagen_sbil_53-letnego_peshehoda',
'https://tula.aif.ru/society/v_shchyokinskom_rayone_za_polmilliona_prodayut_kreshchyonogo_lechebnogo_kota',
'https://tula.aif.ru/incidents/v_tule_iz_pozhara_na_ul_maksimovskogo_evakuirovali_6_chelovek',
'https://tula.aif.ru/money/tulskaya_oblast_okazalas_na_37_meste_v_reytinge_po_dostupnosti_benzina',
'https://tula.aif.ru/sport/tulskiy_akm_ustupil_tolyattinskoy_lade_v_domashnem_matche',
'https://tula.aif.ru/sport/tulyaki_zavoevali_medali_na_kubke_i_pervenstve_rossii_po_velosportu_na_treke',
'https://tula.aif.ru/society/v_tulskoy_oblasti_muzey-usadbu_dvoryaninovo_zakryli_na_remont',
'https://tula.aif.ru/money/tulskiy_sud_rassmotrit_delo_o_bankrotstve_stroitelnoy_kompanii',
'https://tula.aif.ru/incidents/postradavshuyu_v_dtp_zhenshchinu_dostavili_v_bolnicu_tuly_vertolyotom_sanaviacii',
'https://tula.aif.ru/sport/football/tulskiy_arsenal_i_dinamo_mahachkala_sygrali_vnichyu_v_matche_pervoy_ligi']
titleArray = []
dateArray = []
viewArray = []
uniqueArray = []
priceArray = []
sr_priceArray = []
sr_zpArray = []

for link in linkArray:
    print('Формирую данные для статьи: ' + link)
    get_html = requests.get(link)
    html_soup = BeautifulSoup(get_html.content, 'html.parser')

    dates = html_soup.find_all("time", {"itemprop": "datePublished"}, partial=False)
    for date in dates:
        dateArray.append(date.get_text())
        print('Дата публикации: ' + date.get_text())

    titles = html_soup.find_all("h1", {"itemprop": "headline"}, partial=False)
    for title in titles:
        titleArray.append(title.get_text())
        print('Заголовок: ' + title.get_text())

    views = html_soup.find_all("div", {"class": "viewed"}, partial=False)
    for view in views:
        viewArray.append(view.get_text())
        print('Просмотров: ' + view.get_text())


df = pd.DataFrame({'Ссылка': linkArray,
                   'Заголовок': titleArray,
                   'Дата': dateArray,
                   'Просмотры': viewArray,
                   'Уникальность': 0,
                   'Стоимость': '',
                   'Ср. стоимость': '',
                   'Ср. зп': ''
                   })

df.to_excel('./post-list.xlsx')

allLinks = len(linkArray)
cowsay.cow('Экспорт успешно завершён!')
